@HostAddress = https://localhost:44300
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJSLiBSb290IiwiZW1haWwiOiJyb290QGV4YW1wbGUuY29tIiwianRpIjoiODg1OTM4N2EtNzRkMi00MWYxLTk0OTItYzM5ZjNhM2JmMzlkIiwibmJmIjoxNzQ4MzUwNjkyLCJleHAiOjE3NDg5NTU0OTIsImlhdCI6MTc0ODM1MDY5MiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMzMiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo0NDMwMCJ9.I1wBNl1HtwPzxZOsZIy22uoyX-YFWokBLmFnjni6gT4

POST {{HostAddress}}/api/account/login
Content-Type: application/json
Accept: application/json

{
  "username": "R. Root",
  "password": "Syst3m"
}

###

POST {{HostAddress}}/api/account/register
Content-Type: application/json
Accept: application/json

{
  "username": "WebApiUser-123",
  "email": "webapiuser123@example.com",
  "password": "Syst3m"
}

###

GET {{HostAddress}}/api/v1/vehicles/
Accept: application/json

###

GET {{HostAddress}}/api/v1/vehicles/098b6ecc-5714-b09a-36cf-d6280bb3c707
Authorization: Bearer {{token}}
Accept: application/json

###

POST {{HostAddress}}/api/v1/vehicles
Content-Type: application/json
Accept: application/json

{
  "manufacturer": "Honda",
  "model": "Civic",
  "color": "Blue",
  "fuel": "Gasoline",
  "topSpeed": 200,
  "type": "Sedan",
  "registered": "2022-01-01T00:00:00Z"
}

###

PUT {{HostAddress}}/api/v1/vehicles/098b6ecc-5714-b09a-36cf-d6280bb3c707
Content-Type: application/json
Accept: application/json

{
  "manufacturer": "BMW",
  "model": "Isetta",
  "fuel": "Gasoline",
  "color": "Red",
  "type": "Coupe",
  "topSpeed": 50,
  "registered": "1950-01-01T00:00:00Z"
}

###

DELETE {{HostAddress}}/api/v1/vehicles/96ba173e-04ae-3bcd-9986-9e56f0adbf3a
Accept: application/json

